services:
  mysql:
    image: mysql:8.0
    container_name: api_citas_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinica_citas
      MYSQL_USER: clinica_user
      MYSQL_PASSWORD: clinica_pass
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mysql_data: